export const nigerianStates = [
  'Abia',
  'Adamawa',
  'Akwa Ibom',
  'Anambra',
  'Bauchi',
  'Bayelsa',
  'Benue',
  'Borno',
  'Cross River',
  'Delta',
  'Ebonyi',
  'Edo',
  'Ekiti',
  'Enugu',
  'FCT - Abuja',
  'Gombe',
  'Imo',
  'Jigawa',
  'Kaduna',
  'Kano',
  'Katsina',
  'Kebbi',
  'Kogi',
  'Kwara',
  'Lagos',
  'Nasarawa',
  'Niger',
  'Ogun',
  'Ondo',
  'Osun',
  'Oyo',
  'Plateau',
  'Rivers',
  'Sokoto',
  'Taraba',
  'Yobe',
  'Zamfara',
]

export const stateCodeMap: Record<string, string> = {
  Abia: 'ABI',
  Adamawa: 'ADA',
  'Akwa Ibom': 'AKW',
  Anambra: 'ANA',
  Bauchi: 'BAU',
  Bayelsa: 'BAY',
  Benue: 'BEN',
  Borno: 'BOR',
  'Cross River': 'CRS',
  Delta: 'DEL',
  Ebonyi: 'EBO',
  Edo: 'EDO',
  Ekiti: 'EKI',
  Enugu: 'ENU',
  'FCT - Abuja': 'FCT',
  Gombe: 'GOM',
  Imo: 'IMO',
  Jigawa: 'JIG',
  Kaduna: 'KAD',
  Kano: 'KAN',
  Katsina: 'KAT',
  Kebbi: 'KEB',
  Kogi: 'KOG',
  Kwara: 'KWA',
  Lagos: 'LAG',
  Nasarawa: 'NAS',
  Niger: 'NIG',
  Ogun: 'OGN',
  Ondo: 'OND',
  Osun: 'OSU',
  Oyo: 'OYO',
  Plateau: 'PLA',
  Rivers: 'RIV',
  Sokoto: 'SOK',
  Taraba: 'TAR',
  Yobe: 'YOB',
  Zamfara: 'ZAM',
}

export const siteLocations = [
  'Yenagoa SPDC',
  'Ekeremo',
  'Trans Kalabari',
  'Trans Kalabari P2',
  'Owerri-Elele',
  'Elele Omoku',
  'JS Signature',
  'Forces Estate',
  'Head Office (PH)',
  'Airport Nsulu',
  'Abia Government House',
  'Uyo',
  'Igwuruta',
  'Permanent Uni',
  'Epe',
  'Sango Akute',
  'Abeokuta Road',
  'Oyo-Ladoja/Lalupon',
  'Ado Ekiti',
  'Adifa-Isale Oja',
  'Keffi',
  'Karsana',
  'EFCC, Abuja',
  'QBC',
  'Ikoyi Head Office',
]
